#!/bin/bash
set -e

# AI Cortex Sync Utility
# Usage: ./sync.sh [target] [remote_url]

TARGET=${1:-"cursor"}
REMOTE_URL=${2:-"https://raw.githubusercontent.com/nesnilnehc/ai-cortex/main"}

echo "--- 🔄 AI Cortex: Syncing Bridges for [$TARGET] ---"

if [ "$TARGET" == "cursor" ]; then
    OUTPUT_FILE=".cursorrules"
    TMP_FILE=$(mktemp)
    trap 'rm -f "$TMP_FILE"' EXIT

    echo "# Generated by AI Cortex Sync" > "$TMP_FILE"
    echo "## Global Rules" >> "$TMP_FILE"
    curl -sfL "$REMOTE_URL/rules/chinese-technical-standard.md" >> "$TMP_FILE" || { echo "❌ 获取 rules 失败"; exit 1; }

    echo "" >> "$TMP_FILE"
    echo "## Command Mapping" >> "$TMP_FILE"
    curl -sfL "$REMOTE_URL/commands/readme.md" >> "$TMP_FILE" || { echo "❌ 获取 commands 失败"; exit 1; }

    mv "$TMP_FILE" "$OUTPUT_FILE"
    echo "✅ Successfully updated $OUTPUT_FILE"
else
    echo "❌ Unknown target: $TARGET"
    exit 1
fi
